apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapp
  labels:
    app: backendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata:
      labels:
        app: backendapp
    spec:
      containers:
        - name: backendapp
          image: docker.io/ashafqat/backendimage:v1.0
          imagePullPolicy: IfNotPresent
          #imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 300m
              memory: 512Mi