apiVersion: v1
kind: Service
metadata:
  name: backendapp
  labels:
    app: backendapp
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: backendapp